/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capstone;

import com.mysql.cj.xdevapi.Table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author SHIV
 */
public class dbmanager extends javax.swing.JFrame {

    /**
     * Creates new form workpage
     */
    public dbmanager() {
        initComponents();
        showstudentvalues();
        showteachervalues();
    }
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        sname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sclass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sphno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        semail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        saddress = new javax.swing.JTextArea();
        supdate = new javax.swing.JButton();
        snew = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        srno = new javax.swing.JTextField();
        sdel = new javax.swing.JButton();
        sfee = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        teachertable = new javax.swing.JTable();
        tname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tclass = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tphno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tupdate = new javax.swing.JButton();
        tnew = new javax.swing.JButton();
        tdel = new javax.swing.JButton();
        tsubject = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(java.awt.Color.lightGray);

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No", "Student Name", "Class", "Address", "Phone No.", "Email", "Fees"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studenttable.getTableHeader().setReorderingAllowed(false);
        studenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studenttable);
        if (studenttable.getColumnModel().getColumnCount() > 0) {
            studenttable.getColumnModel().getColumn(0).setPreferredWidth(50);
            studenttable.getColumnModel().getColumn(1).setPreferredWidth(150);
            studenttable.getColumnModel().getColumn(2).setPreferredWidth(70);
            studenttable.getColumnModel().getColumn(3).setPreferredWidth(200);
            studenttable.getColumnModel().getColumn(4).setPreferredWidth(100);
            studenttable.getColumnModel().getColumn(5).setPreferredWidth(100);
            studenttable.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jLabel1.setText("Name :");

        jLabel2.setText("Class :");

        jLabel3.setText("Phone No:");

        jLabel4.setText("Email :");

        jLabel5.setText("Address :");

        saddress.setColumns(20);
        saddress.setRows(5);
        jScrollPane2.setViewportView(saddress);

        supdate.setBackground(new java.awt.Color(255, 255, 255));
        supdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        supdate.setText("Update");
        supdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supdate.setFocusPainted(false);
        supdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supdateActionPerformed(evt);
            }
        });

        snew.setBackground(new java.awt.Color(255, 255, 255));
        snew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        snew.setText("New");
        snew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        snew.setFocusPainted(false);
        snew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snewActionPerformed(evt);
            }
        });

        jLabel7.setText("Roll No:");

        srno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srnoActionPerformed(evt);
            }
        });

        sdel.setBackground(new java.awt.Color(255, 255, 255));
        sdel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sdel.setText("Delete");
        sdel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sdel.setFocusPainted(false);
        sdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdelActionPerformed(evt);
            }
        });

        jLabel9.setText("Fee :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(supdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(snew, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(sdel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(sfee, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178)))
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sname)
                            .addComponent(sclass, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(178, 178, 178)
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(srno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(sphno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(srno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(sphno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))
                            .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(sdel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supdate, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snew, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jTabbedPane1.addTab("Student DB", jPanel1);

        jPanel6.setBackground(java.awt.Color.lightGray);

        teachertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher Name", "Class", "Subject", "Phone No.", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        teachertable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        teachertable.getTableHeader().setReorderingAllowed(false);
        teachertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teachertableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(teachertable);
        if (teachertable.getColumnModel().getColumnCount() > 0) {
            teachertable.getColumnModel().getColumn(0).setPreferredWidth(200);
            teachertable.getColumnModel().getColumn(1).setPreferredWidth(70);
            teachertable.getColumnModel().getColumn(2).setPreferredWidth(230);
            teachertable.getColumnModel().getColumn(3).setPreferredWidth(150);
            teachertable.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        jLabel14.setText("Name :");

        jLabel15.setText("Class :");

        jLabel16.setText("Phone No:");

        jLabel17.setText("Email :");

        jLabel18.setText("Subject :");

        tupdate.setBackground(new java.awt.Color(255, 255, 255));
        tupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tupdate.setText("Update");
        tupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tupdate.setFocusPainted(false);
        tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tupdateActionPerformed(evt);
            }
        });

        tnew.setBackground(new java.awt.Color(255, 255, 255));
        tnew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tnew.setText("New");
        tnew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tnew.setFocusPainted(false);
        tnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnewActionPerformed(evt);
            }
        });

        tdel.setBackground(new java.awt.Color(255, 255, 255));
        tdel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tdel.setText("Delete");
        tdel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tdel.setFocusPainted(false);
        tdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel14)
                        .addGap(16, 16, 16)
                        .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(tphno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(tclass, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(tsubject, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(tupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(tnew, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(tdel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tphno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(tclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(tsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnew, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tdel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Teacher DB", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 97, 1000, 600));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manager_50px.png"))); // NOI18N
        jLabel6.setText("COLLEGE MANAGER");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back_to_60px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdelActionPerformed
        try {
            Connection con = DriverManager.getConnection(url,"root","");
            String query = "delete from teacher where name='"+tname.getText()+"'";
            Statement s = con.createStatement();
            int sel = JOptionPane.showConfirmDialog(null, "Really delete "+tname.getText()+" ?", "Confirm Delete",JOptionPane.YES_NO_OPTION);
            if(sel == JOptionPane.YES_OPTION){
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Deleted Successfully!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Cancelled Operation!");
            }
            DefaultTableModel dm = (DefaultTableModel)teachertable.getModel();
            dm.setRowCount(0);
            showteachervalues();
            s.close();
            con.close();
        } catch (Exception e) {e.printStackTrace();
        }     
    }//GEN-LAST:event_tdelActionPerformed

    private void tnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnewActionPerformed
        try{    
            Connection con = DriverManager.getConnection(url,"root","");
            String query = "insert into teacher(name,class,subject,phno,email) values('"+tname.getText()+"','"+tclass.getText()+"','"+tsubject.getText()+"','"+tphno.getText()+"','"+temail.getText()+"')";
            Statement s = con.createStatement();
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, ""+tname.getText()+" added successfully!");
            DefaultTableModel tm = (DefaultTableModel)teachertable.getModel();
            tm.setRowCount(0);
            showteachervalues();
            tname.setText("");
            tclass.setText("");
            tsubject.setText("");
            tphno.setText("");
            temail.setText("");
            con.close();
            s.close();
        } catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_tnewActionPerformed

    private void tupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tupdateActionPerformed
        try{
            int i = teachertable.getSelectedRow();
            DefaultTableModel dm = (DefaultTableModel)teachertable.getModel();
            String name = dm.getValueAt(i, 0).toString();
            Connection con = DriverManager.getConnection(url,"root","");
            Statement s = con.createStatement();
            String query = "update teacher set name='"+tname.getText()+"',class= '"+tclass.getText()+"',subject='"+tsubject.getText()+"',phno='"+tphno.getText()+"',email='"+temail.getText()+"' where name='"+name+"'";
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, ""+tname.getText()+" updated successfully!");
            DefaultTableModel tm = (DefaultTableModel)teachertable.getModel();
            tm.setRowCount(0);
            showteachervalues();
            tname.setText("");
            tclass.setText("");
            tsubject.setText("");
            tphno.setText("");
            temail.setText("");
            con.close();
            s.close();
        }catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_tupdateActionPerformed

    private void teachertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teachertableMouseClicked
        int i = teachertable.getSelectedRow();
        TableModel tm = teachertable.getModel();
        tname.setText(tm.getValueAt(i, 0).toString());
        tclass.setText(tm.getValueAt(i, 1).toString());
        tsubject.setText(tm.getValueAt(i, 2).toString());
        tphno.setText(tm.getValueAt(i, 3).toString());
        temail.setText(tm.getValueAt(i, 4).toString());    
    }//GEN-LAST:event_teachertableMouseClicked

    private void sdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdelActionPerformed
        try {
            Connection con = DriverManager.getConnection(url,"root","");
            String query = "delete from students where name='"+sname.getText()+"'";
            Statement s = con.createStatement();
            int sel = JOptionPane.showConfirmDialog(null, "Really delete "+sname.getText()+" ?", "Confirm Delete",JOptionPane.YES_NO_OPTION);
            if(sel == JOptionPane.YES_OPTION){
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Deleted Successfully!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Cancelled Operation!");
            }
            DefaultTableModel dm = (DefaultTableModel)studenttable.getModel();
            dm.setRowCount(0);
            showstudentvalues();
            s.close();
            con.close();
        } catch (Exception e) {e.printStackTrace();
        }
  
    }//GEN-LAST:event_sdelActionPerformed

    private void srnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srnoActionPerformed

    private void snewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snewActionPerformed
        try {
            Connection con = DriverManager.getConnection(url,"root","");
            String query = "insert into students(rno,name,class,address,phno,email,fee) values('"+srno.getText()+"','"+sname.getText()+"','"+sclass.getText()+"','"+saddress.getText()+"','"+sphno.getText()+"','"+semail.getText()+"','"+sfee.getText()+"')";
            Statement s = con.createStatement();
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, ""+sname.getText()+" added successfully!");
            DefaultTableModel tm = (DefaultTableModel)studenttable.getModel();
            tm.setRowCount(0);
            showstudentvalues();
            sname.setText("");
            srno.setText("");
            sclass.setText("");
            saddress.setText("");
            sphno.setText("");
            semail.setText("");
            sfee.setText("");
            con.close();
            s.close();
        } catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_snewActionPerformed

    private void supdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supdateActionPerformed
        try{
            int i = studenttable.getSelectedRow();
            DefaultTableModel dm = (DefaultTableModel)studenttable.getModel();
            String name = dm.getValueAt(i, 1).toString();
            Connection con = DriverManager.getConnection(url,"root","");
            Statement s = con.createStatement();
            String query = "update students set rno='"+srno.getText()+"',name='"+sname.getText()+"',class= '"+sclass.getText()+"',address='"+saddress.getText()+"',phno='"+sphno.getText()+"',email='"+semail.getText()+"',fee='"+sfee.getText()+"' where name='"+name+"'";
            s.executeUpdate(query);
            JOptionPane.showMessageDialog(null, ""+sname.getText()+" updated successfully!");
            DefaultTableModel tm = (DefaultTableModel)studenttable.getModel();
            tm.setRowCount(0);
            showstudentvalues();
            sname.setText("");
            srno.setText("");
            sclass.setText("");
            saddress.setText("");
            sphno.setText("");
            semail.setText("");
            sfee.setText("");
            con.close();
            s.close();
        }catch (Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_supdateActionPerformed

    private void studenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttableMouseClicked
        int i = studenttable.getSelectedRow();
        TableModel tm = studenttable.getModel();
        srno.setText(tm.getValueAt(i, 0).toString());
        sname.setText(tm.getValueAt(i, 1).toString());
        sclass.setText(tm.getValueAt(i, 2).toString());
        saddress.setText(tm.getValueAt(i, 3).toString());
        sphno.setText(tm.getValueAt(i, 4).toString());
        semail.setText(tm.getValueAt(i, 5).toString());
        sfee.setText(tm.getValueAt(i, 6).toString());
    }//GEN-LAST:event_studenttableMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        menu m = new menu();
        dispose();
        m.show();
    }//GEN-LAST:event_jLabel8MouseClicked

    String url = "jdbc:mysql://localhost:3306/capstone?zeroDateTimeBehavior=convertToNull";
     public void showstudentvalues(){
     try{
            Connection con = DriverManager.getConnection(url,"root","");
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select * from students");
            DefaultTableModel tm = (DefaultTableModel)studenttable.getModel();
            Object[] row = new Object[7];
            while(r.next()){
            row[0] = r.getInt("rno");
            row[1] = r.getString("name");
            row[2] = r.getString("class");
            row[3] = r.getString("address");
            row[4] = r.getString("phno");
            row[5] = r.getString("email");
            row[6] = r.getInt("fee");
            tm.addRow(row);
            }
            con.close();
            s.close();
            r.close();     
    }catch(Exception e){e.printStackTrace();}} 
     
    public void showteachervalues(){
    try{
            Connection con = DriverManager.getConnection(url,"root","");
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select * from teacher");
            DefaultTableModel tm = (DefaultTableModel)teachertable.getModel();
            Object[] row = new Object[5];
            while(r.next()){
            row[0] = r.getString("name");
            row[1] = r.getString("class");
            row[2] = r.getString("subject");
            row[3] = r.getString("phno");
            row[4] = r.getString("email");
            tm.addRow(row);
            }
            con.close();
            s.close();
            r.close();     
    }catch(Exception e){e.printStackTrace();}
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dbmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dbmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dbmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dbmanager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbmanager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea saddress;
    private javax.swing.JTextField sclass;
    private javax.swing.JButton sdel;
    private javax.swing.JTextField semail;
    private javax.swing.JTextField sfee;
    private javax.swing.JTextField sname;
    private javax.swing.JButton snew;
    private javax.swing.JTextField sphno;
    private javax.swing.JTextField srno;
    private javax.swing.JTable studenttable;
    private javax.swing.JButton supdate;
    private javax.swing.JTextField tclass;
    private javax.swing.JButton tdel;
    private javax.swing.JTable teachertable;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tname;
    private javax.swing.JButton tnew;
    private javax.swing.JTextField tphno;
    private javax.swing.JTextField tsubject;
    private javax.swing.JButton tupdate;
    // End of variables declaration//GEN-END:variables
}
